### ISSUE TITLE
Does it track routing

### ISSUE THREAD

**Issue by ambroiseRabier** [Arnaud73/ngx-matomo#17]
Does it automatically tracks angular routing? If not by default, how do you do it (would be a nice add to the README).

**Comment by Arnaud73** [comment]
It is a feature that I will provide (almost ready), however, since it is going to require RxJS as a peerDependancy, it will break the compatibility between Angular 5 and later releases. That's the reason why I defered its implementation.

**Comment by SublimeProphets** [comment]
First of all: thank you a lot for developing this great library.
second, I'd also appreciate that functionality, i think that must be useful for like 80% of the users.
However, instead of delaying the implementation, you could may just ignore angular5, they could probably use the rxjs-compat to make it run.

**Comment by ambroiseRabier** [comment]
I have rebased my pull request, can you please review it? There is page tracking instructions on it.

**Comment by ambroiseRabier** [comment]
I have made my own version of this lib with route tracking [here][https://github.com/ambroiseRabier/ngx-matomo] for anyone interested.

**Comment by Arnaud73** [comment]
I know, it's been overdue, but track routing is now properly implemented.

It can be tested in the 1.0 RC release: https://www.npmjs.com/package/ngx-matomo/v/1.0.0-rc.0

Version 1.0 shall come very soon once Angular 12 is out this month.
