### ISSUE TITLE
The code in the demo seem to be not correct

### ISSUE THREAD

**Issue by alljamin** [Arnaud73/ngx-matomo#23]
In `app.component.ts` you have:
```
constructor(private matomoInjector: MatomoInjector, 
private matomoTracker: MatomoTracker) {
    this.matomoInjector.init(
      'http://ngx.matomo.cloud/',
      1,
      '//cdn.matomo.cloud/ngx.matomo.cloud/matomo.js'
    );
  }
```
Which will result in the following error:

>Expected 2 arguments, but got 3.

Is this the correct usage?
```
constructor(private matomoInjector: MatomoInjector, 
private matomoTracker: MatomoTracker) {
    this.matomoInjector.init(
      'http://ngx.matomo.cloud/',
      1
    );
  }
```

**Comment by alljamin** [comment]
Just realised that the change has been merged but not published. Do you think you can get around to publishing it sometime soon @Arnaud73?

**Comment by Arnaud73** [comment]
Hello,

Yes, there are many updates that are still not published, especially since I'm finishing the work towards release 1.0 which will be a big evolution, with simpler usage yet more powerful.

I will hopefully finish the work in the coming weeks, yet, I can't find as much time as I would like.

If you would be interested into testing a beta of this version, let me know!
