### ISSUE TITLE
Could it using an old version of the code?

### ISSUE THREAD

**Issue by pam81** [Arnaud73/ngx-matomo#38]
Hi I review the code and it's adding piwik.js like this

g.src = !!scriptUrl ? scriptUrl : u + 'piwik.js';

but the new code is adding matomo.js

g.src=u+'matomo.js';
Is it working right?

**Comment by Arnaud73** [comment]
Hi,

I had this discussion with the Matomo team some time ago (https://forum.matomo.org/t/tracking-code-evolutions/33247). The old URLs (with `piwik` instead of `matomo`) are working for old and new instances of Matomo, whereas the `matomo` ones only work in new instances. As a result I'll stick with the old ones since they work for everybody.

In the coming 1.0 release, injecting the tracker has been completely modified, and URLs will be user provided instead, so the problem will disappear.
