### ISSUE TITLE
Property 'forRoot' does not exist on type 'typeof MatomoModule'

### ISSUE THREAD

**Issue by freedbrd** [Arnaud73/ngx-matomo#55]
I faced the issue when I installed the ngx-module and tried to import this one. 

![image](https://user-images.githubusercontent.com/45984060/118765247-78b0a080-b883-11eb-8767-94eb45302e98.png)

**Comment by freedbrd** [comment]
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.12
Node: 14.15.4
OS: win32 x64

Angular: 9.1.12
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.12
@angular-devkit/build-angular     0.901.12
@angular-devkit/build-optimizer   0.901.12
@angular-devkit/build-webpack     0.901.12
@angular-devkit/core              9.1.12
@angular-devkit/schematics        9.1.12
@angular/cdk                      9.2.4
@angular/material                 9.2.4
@ngtools/webpack                  9.1.12
@schematics/angular               9.1.12
@schematics/update                0.901.12
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

**Comment by Arnaud73** [comment]
The reason is simple: you read the README on Github which already speaks about the new release which is not yet published as the latest release on NPM (it is still a release candidate).

Since you are using Angular 9, I'd suggest you go with version 1.0.0-rc.0 (https://www.npmjs.com/package/ngx-matomo/v/1.0.0-rc.0) which supports this platform.

Don't bother to use 0.1.4 since it is now mostly outdated for new Angular applications.
