### ISSUE TITLE
Angular 13 compatibility

### ISSUE THREAD

**Issue by nicolasalcina** [Arnaud73/ngx-matomo#68]
in Angular 13, NgModuleFactoryLoader was removed

See here : https://update.angular.io/?l=3&v=12.0-13.0
last point : The route package no longer exports SpyNgModuleFactoryLoader and DeprecatedLoadChildren. In case you use them, make sure you remove their corresponding import statements.

error on build :
Error: node_modules/ngx-matomo/node_modules/@angular/router/router.d.ts:21:10 - error TS2305: Module '"@angular/core"' has no exported member 'NgModuleFactoryLoader'.

**Comment by sinsunsan** [comment]
Any chance to release an angular 13 version @Arnaud73?

Or @nicolasalcina  to do a fork + MR to fix the problem?

**Comment by sinsunsan** [comment]
@nicolasalcina did you found solution? 
I was preparing myself to do a fork and dive into the problem, but maybe it is already fixed for you?

**Comment by sinsunsan** [comment]
I found those issue https://github.com/angular/universal/issues/2451
and the changelog referring to the deprecation https://github.com/angular/angular/blob/master/CHANGELOG.md#1300-2021-11-03

but I don't see any use of this deprecated import in the project....

@nicolasalcina

**Comment by sinsunsan** [comment]
Ok I got it https://github.com/Arnaud73/ngx-matomo/pull/69/files
It was only needed to update the peerDependencies to angular 13 minimum in the package.json of the lib. 

Here is an MR https://github.com/Arnaud73/ngx-matomo/pull/69/files

I also did a temporary deploy with name  `sinsunsan-ngx-matomo` `"sinsunsan-ngx-matomo": "0.1.5"` so that we don't need to wait @Arnaud73  to merge

**Comment by nicolasalcina** [comment]
Perfect thank you
Sorry, got not enough time to watch this, I stayed in ng12 for this time ;)

**Comment by jurizfadv** [comment]
Any update on Angular 13 compatibility?

**Comment by khaled4vokalz** [comment]
@Arnaud73 ,
Can you please take a look at this PR https://github.com/Arnaud73/ngx-matomo/issues/68#issuecomment-986940538? And merge if applicable?

**Comment by KamranTaghaddos** [comment]
> Ok I got it https://github.com/Arnaud73/ngx-matomo/pull/69/files It was only needed to update the peerDependencies to angular 13 minimum in the package.json of the lib.
> 
> Here is an MR https://github.com/Arnaud73/ngx-matomo/pull/69/files
> 
> I also did a temporary deploy with name `sinsunsan-ngx-matomo` `"sinsunsan-ngx-matomo": "0.1.5"` so that we don't need to wait @Arnaud73 to merge

Thank you very much. You saved my day.

**Comment by mayur-gharat** [comment]
@sinsunsan , Is this issue resolved? I am still facing issue while upgrading my application from Agnular12 to Angular13

**Comment by ambarkiy** [comment]
Does anyone know if the matomo package is maintained? Because we have been waiting for the version upgrade to Angular 13 for several months.
A pull request is in progress, but apparently the owner does not want to integrate it, or he is too busy. It's a shame, I don't think I'm the only one in this situation....

**Comment by jonhamm** [comment]
We chose to switch to @ngx-matomo/tracker
where we got an immediate fix to a configuration issue - so actively maintained!
Works perfectly and no issues found after the fix

**Comment by ambarkiy** [comment]
I just looked, the package looks very elegant and intuitive.
I will integrate it in the week.

Thanks for your help.
